1주차/PGS_교점에별만들기_베베.py
1주차/PGS_두개뽑아서더하기_베베.py
1주차/PGS_모의고사_베베.py
1주차/PGS_시저암호_베베.py
1주차/PGS_콜라츠추측_베베.py

```
............./´¯/).............(\¯`\
............/....//..............\\....\
.........../....//................\\....\
...../´¯/..../´¯\............./¯`\....\¯`\..
.././.../..../..../.\......_|.\....\....\---\.\..
(.(....(....(..../.)...)....(..(.\....)....)----.).)
.\................\/.../....\...\/................/
..\................. /........\................../
....\..............(............)............../
......\.............\.........../............./
.......|..............|..........|..............|
```

feat: 1주차 - 베베

---

2주차/PGS_완주하지못한선수_우가.py
2주차/PGS_입국심사_우가.py
2주차/PGS_주식가격_우가.py
2주차/PGS_키패드누르기_우가.py
2주차/PGS_타겟넘버_우가.py
2주차/PGS_피보나치수_우가.py

feat: 2주차 - 우가

---

2주차/PGS_완주하지못한선수_채채.py
2주차/PGS_입국심사_채채.py
2주차/PGS_주식가격_채채.py
2주차/PGS_타겟넘버_채채.py
2주차/PGS_피보나치수_채채.py

feat: 2주차 - 채채

---

.idea/.gitignore
.idea/AlgorithmStudyOfDestruction.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
2주차/PGS_완주하지못한선수_저문.py
2주차/PGS_입국심사_저문.py
2주차/PGS_주식가격_저문.py
2주차/PGS_피보나치수_저문.py

feat: 2주차 - 저문

---

3주차/PGS_신고결과받기.py
3주차/PGS_이상한문자만들기.py
3주차/PGS_조이스틱.py
3주차/PGS_하노이의탑.py
3주차/PGS_행렬테두리회전하기.py

feat: 3주차 - 라온

---

3주차/PGS_신고결과받기_채채.py
3주차/PGS_이상한문자만들기_채채.py
3주차/PGS_조이스틱_채채.py
3주차/PGS_하노이의탑_채채.py

하노이탑 혼자풀지않고 구글링했습니다 몰라서..
3번 못풀었습니다..
1번 너무어렵당

feat: 3주차 - 채채

---

.idea/.gitignore
.idea/AlgorithmStudyOfDestruction.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
2주차/PGS_완주하지못한선수_베베.py
2주차/PGS_입국심사_베베.py
2주차/PGS_주식가격_베베.py
2주차/PGS_키패드누르기_베베.py
2주차/PGS_타겟넘버_베베.py
2주차/PGS_피보나치수_베베.py
3주차/신고_결과_받기_베베.py
3주차/이상한_문자_만들기_베베.java
3주차/조이스틱_베베.java
3주차/하노이의_탑_베베.py
3주차/행렬_테두리_회전_베베.java

몇 문제 파이썬으로 파이쏘닉하게 풀 엄두가 안나서 알고리즘 틀딱 언어 자바로 풀었습니다.
+ 오늘의 tmi 
캠퍼스 가기 싫다~ 이제 햄버거 먹으러갑니다~~

feat: 3주차 - 베베

---

4주차/PGS_H-index_라온.py
4주차/PGS_문자열다루기기본_라온.py
4주차/PGS_순위검색_라온.py
4주차/PGS_전화번호목록_라온.py
4주차/PGS_카펫_라온.py
4주차/PGS_해시_라온.py

feat: 4주차 - 라온

---

4주차/PGS_H-Index_디노.py
4주차/PGS_문자열다루기기본_디노.py
4주차/PGS_카펫_디노.py

3문제 못풀었습니다. 
모범을 보여야 하는데.. 죄송한 마음이 큽니다..

feat: 4주차 - 디노

---

4주차/PGS_H-Index_우가.py
4주차/PGS_N으로표현_우가.py
4주차/PGS_문자열다루기기본_우가.py
4주차/PGS_전화번호목록_우가.py
4주차/PGS_카펫_우가.py

feat: 4주차 우가

---

4주차/PGS_H-Index_베베.py
4주차/PGS_N으로_표현_베베.py
4주차/PGS_문자열다루기기본_베베.java
4주차/PGS_카펫_베베.java

feat: 4주차 - 베베

---

6주차/PGS_디스크컨트롤러_우가.py
6주차/PGS_모음사전_우가.py
6주차/PGS_문자열내마음대로정렬하기_우가.py
6주차/PGS_소수찾기_우가.py
6주차/PGS_징검다리_우가.py
6주차/PGS_튜플_우가.py

feat: 6주차 - 우가

---

6주차/PGS_디스크컨트롤러_디노.py
6주차/PGS_모음사전_디노.py
6주차/PGS_문자열내마음대로정렬하기.py
6주차/PGS_소수찾기_디노.py
6주차/PGS_징검다리_디노.py
6주차/PGS_튜플_디노.py

소수 찾기는 풀어 놓고 다른 사람들 풀이 복붙해서 실행해 봤었는데 그게 프로그래머스에 저장됐네여;;
다시 풀 시간이 없을 것 같아 일단 제출합니다

feat: 6주차 - 디노

---

3주차/PGS_하노이의탑_디노.py
4주차/PGS_N으로표현_디노.py
4주차/PGS_순위검색_디노.py
4주차/PGS_전화번호목록_디노.py
5주차/PGS_2개이하로다른비트_디노.py
6주차/PGS_소수찾기_디노.py

지난번에 못푼 문제랑 다른 풀이 보고 싶은 문제들 조금 더 봐봤습니다.. 왤케 어렵냐 벽느낌;;

feat: 7, 8주차 - 디노

---

2주차/PGS_입국심사_라온.py
4주차/PGS_N으로표현_라온.py
5주차/PGS_여행경로_라온.py
6주차/PGS_디스크컨트롤러_라온.py

입국심사
N으로 표현
여행경로
디스크 컨트롤러
---
순위검색
하노이의 탑

feat: 7, 8주차 - 라온

---

7, 8주차/PGS_가장큰수_우가.py
7, 8주차/PGS_단어변환_우가.py
7, 8주차/PGS_베스트앨범_우가.py
7, 8주차/PGS_의상_우가.py
7, 8주차/PGS_체육복_우가.py

feat: 7, 8주차 - 우가

---

7,8주차/디스크_컨트롤러_베베.py
7,8주차/문자열다루기_베베.py
7,8주차/여행경로_베베.py
7,8주차/징검다리_베베.py

기존에 자바로 풀었던 문제를 파이썬으로 풀어보았습니다!

feat: 7,8주차 - 베베

---

9주차/BOJ_1010_다리놓기_디노.py
9주차/BOJ_10815_숫자카드_디노.py
9주차/BOJ_1193_분수찾기_디노.py
9주차/BOJ_1365_꼬인전깃줄_디노.py
9주차/BOJ_2343_기타레슨_디노.py
9주차/BOJ_2467_용액_디노.py

feat: 9주차 -디노

---

9주차/BGS_1010_다리놓기_우가.py
9주차/BGS_10815_숫자카드_우가.py
9주차/BGS_1193_분수찾기_우가.py
9주차/BGS_2343_기타레슨_우가.py
9주차/BGS_2467_용액_우가.py

feat: 9주차 - 우가

---

9주차/BOJ_기타레슨_리오.py
9주차/BOJ_꼬인전깃줄_리오.py
9주차/BOJ_다리놓기_리오.py
9주차/BOJ_분수찾기_리오.py
9주차/BOJ_숫자카드_리오.py
9주차/BOJ_용액_리오.py

죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다 죄송합니다

feat: 9주차 - 리오

---

9주차/BOJ_1010_다리놓기_라온.py
9주차/BOJ_10815_숫자카드_라온.py
9주차/BOJ_1193_분수찾기_라온.py
9주차/BOJ_2343_기타레슨_라온.py
9주차/BOJ_2467_용액_라온.py

feat: 9주차 - 라온

---

10주차/BOJ_10610_30_라온.py
10주차/BOJ_10988_팰린드롬인지확인하기_라온.py
10주차/BOJ_1100_하얀칸_라온.py
10주차/BOJ_1958_LCS3_라온.py
10주차/BOJ_2800_괄호제거_라온.py
10주차/BOJ_5582_공통부분문자열_라온.py

feat: 10주차 - 라온

---

10주차/BOJ_10610_30_저문.py
10주차/BOJ_10988_팰린드롬인지확인하기 _저문.py
10주차/BOJ_1100_하얀칸_저문.py
10주차/BOJ_2800_괄호제거_저문.py
10주차/BOJ_5582_공통부분문자열_저문.py

dp에 많이 약해서 공통 부분 문자열 문제는 답지를 참고하여 공부했습니다.
추가적으로 이어서 응용된 4번째 문제도 시도해볼게요~

feat: 10주차 - 저문

---

10주차/BOJ_10610_30_디노.py
10주차/BOJ_10988_팰린드롬인지확인하기_디노.py
10주차/BOJ_1100_하얀칸_디노.py
10주차/BOJ_1985_LCS3_디노.py
10주차/BOJ_2800_괄호제거_디노.py
10주차/BOJ_5582_공통부분문자열_디노.py

https://calcproject.tistory.com/150

feat: 10주차 - 디노

---

10주차/BOJ_30_채채.py
10주차/BOJ_LCS3_채채.py
10주차/BOJ_공통부분문자열_채채.py
10주차/BOJ_괄호제거_채채.py
10주차/BOJ_팰린드롬인지확인하기_채채.py
10주차/BOJ_하얀칸_채채.py

feat: 10주차 - 채채

---

10주차/BGS_10610_30_우가.py
10주차/BGS_10998_팰린드롬인지확인하기_우가.py
10주차/BGS_1100_하얀칸_우가.py
10주차/BGS_1958_LCS3_우가.py
10주차/BGS_2800_괄호제거_우가.py

feat: 10주차 - 우가

---

11주차/BGS_11660_구간합구하기5_우가.py
11주차/BGS_1946_신입사원_우가.py
11주차/BGS_2167_2차원배열의합_우가.py

feat: 11, 12주차 - 우가

---

11주차/BOJ_11660_구간합구하기5_라온.py
11주차/BOJ_14503_로봇청소기_라온.py
11주차/BOJ_1946_신입사원_라온.py
11주차/BOJ_2167_2차원배열의합_라온.py
11주차/BOJ_2293_동전1_라온.py
11주차/BOJ_2468_안전영역_라온.py
12주차/BOJ_2563_색종이_라온.py
12주차/BOJ_2573_빙산_라온.py
12주차/BOJ_2578_빙고_라온.py

feat: 11, 12주차 - 라온

---

13주차/BOJ_1439_뒤집기.py
13주차/BOJ_1520_내리막길_디노.py
13주차/BOJ_1744_수묶기_디노.py
13주차/BOJ_2217_로프_디노.py
13주차/BOJ_2810_컵홀더_디노.py
13주차/BOJ_3190_뱀_디노.py

feat: 13주차 - 디노

---

14주차/BOJ_1197_최소스패닝트리_라온.py
14주차/BOJ_2446_별찍기_라온.py
14주차/BOJ_2644_촌수계산_라온.py
14주차/BOJ_9372_상근이의여행_라온.py
14주차/BOJ_9655_돌게임_라온.py

feat: 14주차 - 라온

---

14주차/BOJ_1197_최소스패닝트리_디노.py
14주차/BOJ_13460_구슬탈출_디노.py
14주차/BOJ_2446_별찍기_디노.py
14주차/BOJ_2644_촌수계산_디노.py
14주차/BOJ_9372_상근이의여행_디노.py
14주차/BOJ_9655_돌게임_디노.py

feat: 14주차 - 디노

---

15주차/BOJ_11478_서로다른부분문자열의개수_라온.py
15주차/BOJ_14501_퇴사_라온.py
15주차/BOJ_1717_집합의표현_라온.py
15주차/BOJ_17478_재귀함수가뭔가요_라온.py
15주차/PGS_의상_라온.py
15주차/PGS_정수삼각형_라온.py

~~아직 다 못풀었습니다 .. 오늘 중으로 마저 풀어서 낼게요 .. !!!!~~
다풀었다! 1:30 AM

feat: 15주차 - 라온

---

16주차/BOJ_14940_쉬운최단거리_라온.py
16주차/BOJ_18110_solved.ac_라온.py
16주차/BOJ_21736_헌내기는친구가필요해_라온.py
16주차/PGS_그래프_라온.py
16주차/PGS_스킬트리_라온.py

feat: 16주차 - 라온

---

16주차/BOJ_2294_동전2_라온.py
16주차/PGS_가장먼노드_라온.py
17주차/BOJ_20529_가장가까운세사람의심리적거리_라온.py
17주차/BOJ_2096_내려가기_라온.py
17주차/BOJ_2941_크로아티아알파벳_라온.py
17주차/BOJ_5635_생일_라온.py
17주차/PGS_네트워크_라온.py
17주차/PGS_보석쇼핑_라온.py

feat: 17주차 - 라온

---

18주차/BOJ_2583_영역구하기_디노.java
18주차/BOJ_4811_알약_디노.java
18주차/PGS_괄호회전하기_디노.java
18주차/PGS_숫자문자열과영단어_디노.java
18주차/PGS_압축_디노.java
18주차/PGS_이진변환반복하기_디노.java

feat: 18주차 - 디노

---

19주차/BOJ_1238_파티_디노.py
19주차/BOJ_2565_전깃줄_디노.py
19주차/BOJ_2776_암기왕_디노.java
19주차/BOJ_2776_암기왕_디노.py
19주차/PGS_거리두기확인하기_디노.py
19주차/PGS_짝지어제거하기_디노.py
19주차/PGS_호텔방배정_디노.py

feat: 19주차 - 디노

---

19주차/BOJ_2776_암기왕_라온.py
19주차/PGS_거리두기확인하기_라온.py
19주차/PGS_짝지어제거하기_라온.py
19주차/PGS_호텔방배정_라온.py

feat: 19주차 - 라온

---

20주차/PGS_가장큰수_디노.py
20주차/PGS_단어변환_디노.py
20주차/PGS_문자열압축_디노.py
20주차/PGS_불량사용자_디노.py
20주차/PGS_오픈채팅방_디노.py
20주차/PGS_줄서는방법.py

feat: 20주차 - 디노

---

20주차/PGS_가장큰수_라온.py
20주차/PGS_단어변환_라온.py
20주차/PGS_문자열압축_라온.py
20주차/PGS_불량사용자_라온.py
20주차/PGS_오픈채팅방_라온.py
20주차/PGS_줄서는방법_라온.py

feat: 20주차 - 라온

---

21주차/BOJ_13458_시험감독_디노.py
21주차/BOJ_14499_주사위굴리기_디노.py
21주차/BOJ_2589_보물섬_디노.py
21주차/PGS_수식최대화_디노.py
21주차/PGS_신규아이디추천_디노.py
21주차/PGS_행렬의곱셈_디노.py

~~4번 문제 빠르게 풀고 추가하겠습니다..~~ 추가했지~

feat: 21주차 - 디노
